- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.6.1
  hooks:
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: flake8
  - id: trailing-whitespace

- repo: git://github.com/pre-commit/mirrors-pylint
  sha: v1.6.4
  hooks:
  - id: pylint
